apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: fntkg/serverless-api:0.1.0
        ports:
        - containerPort: 80
      # Improves application resilience by ensuring pods are distributed evenly across different zones.
      # This prevents excessive workload concentration in a single failure domain, reducing the impact of zone outages
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: my-api
